-- PARTICIPANTES
INSERT INTO TB_PARTICIPANTE (NM_PARTICIPANTE, DS_EMAIL, TP_PARTICIPANTE) VALUES
('Participante 1', 'participante.1@example.com', 'Aluno'),
('Participante 2', 'participante.2@example.com', 'Aluno'),
('Participante 3', 'participante.3@example.com', 'Aluno'),
('Participante 4', 'participante.4@example.com', 'Aluno'),
('Participante 5', 'participante.5@example.com', 'Professor'),
('Participante 6', 'participante.6@example.com', 'Professor'),
('Participante 7', 'participante.7@example.com', 'Aluno'),
('Participante 8', 'participante.8@example.com', 'Aluno'),
('Participante 9', 'participante.9@example.com', 'Professor'),
('Participante 10', 'participante.10@example.com', 'Aluno'),
('Participante 11', 'participante.11@example.com', 'Professor'),
('Participante 12', 'participante.12@example.com', 'Aluno'),
('Participante 13', 'participante.13@example.com', 'Professor'),
('Participante 14', 'participante.14@example.com', 'Aluno'),
('Participante 15', 'participante.15@example.com', 'Professor'),
('Participante 16', 'participante.16@example.com', 'Aluno'),
('Participante 17', 'participante.17@example.com', 'Aluno'),
('Participante 18', 'participante.18@example.com', 'Aluno'),
('Participante 19', 'participante.19@example.com', 'Aluno'),
('Participante 20', 'participante.20@example.com', 'Professor'),
('Participante 21', 'participante.21@example.com', 'Comunidade'),
('Participante 22', 'participante.22@example.com', 'Comunidade'),
('Participante 23', 'participante.23@example.com', 'Professor'),
('Participante 24', 'participante.24@example.com', 'Professor'),
('Participante 25', 'participante.25@example.com', 'Comunidade'),
('Participante 26', 'participante.26@example.com', 'Comunidade'),
('Participante 27', 'participante.27@example.com', 'Comunidade'),
('Participante 28', 'participante.28@example.com', 'Comunidade'),
('Participante 29', 'participante.29@example.com', 'Aluno'),
('Participante 30', 'participante.30@example.com', 'Comunidade'),
('Participante 31', 'participante.31@example.com', 'Professor'),
('Participante 32', 'participante.32@example.com', 'Comunidade'),
('Participante 33', 'participante.33@example.com', 'Professor'),
('Participante 34', 'participante.34@example.com', 'Professor'),
('Participante 35', 'participante.35@example.com', 'Comunidade'),
('Participante 36', 'participante.36@example.com', 'Professor'),
('Participante 37', 'participante.37@example.com', 'Aluno'),
('Participante 38', 'participante.38@example.com', 'Aluno'),
('Participante 39', 'participante.39@example.com', 'Comunidade'),
('Participante 40', 'participante.40@example.com', 'Professor'),
('Participante 41', 'participante.41@example.com', 'Comunidade'),
('Participante 42', 'participante.42@example.com', 'Comunidade'),
('Participante 43', 'participante.43@example.com', 'Aluno'),
('Participante 44', 'participante.44@example.com', 'Comunidade'),
('Participante 45', 'participante.45@example.com', 'Aluno'),
('Participante 46', 'participante.46@example.com', 'Comunidade'),
('Participante 47', 'participante.47@example.com', 'Professor'),
('Participante 48', 'participante.48@example.com', 'Professor'),
('Participante 49', 'participante.49@example.com', 'Professor'),
('Participante 50', 'participante.50@example.com', 'Comunidade'),
('Participante 51', 'participante.51@example.com', 'Comunidade'),
('Participante 52', 'participante.52@example.com', 'Aluno'),
('Participante 53', 'participante.53@example.com', 'Aluno'),
('Participante 54', 'participante.54@example.com', 'Professor'),
('Participante 55', 'participante.55@example.com', 'Comunidade'),
('Participante 56', 'participante.56@example.com', 'Aluno'),
('Participante 57', 'participante.57@example.com', 'Comunidade'),
('Participante 58', 'participante.58@example.com', 'Professor'),
('Participante 59', 'participante.59@example.com', 'Aluno'),
('Participante 60', 'participante.60@example.com', 'Comunidade'),
('Participante 61', 'participante.61@example.com', 'Aluno'),
('Participante 62', 'participante.62@example.com', 'Comunidade'),
('Participante 63', 'participante.63@example.com', 'Comunidade'),
('Participante 64', 'participante.64@example.com', 'Comunidade'),
('Participante 65', 'participante.65@example.com', 'Aluno'),
('Participante 66', 'participante.66@example.com', 'Comunidade'),
('Participante 67', 'participante.67@example.com', 'Comunidade'),
('Participante 68', 'participante.68@example.com', 'Comunidade'),
('Participante 69', 'participante.69@example.com', 'Aluno'),
('Participante 70', 'participante.70@example.com', 'Aluno'),
('Participante 71', 'participante.71@example.com', 'Aluno'),
('Participante 72', 'participante.72@example.com', 'Comunidade'),
('Participante 73', 'participante.73@example.com', 'Comunidade'),
('Participante 74', 'participante.74@example.com', 'Professor'),
('Participante 75', 'participante.75@example.com', 'Professor'),
('Participante 76', 'participante.76@example.com', 'Comunidade'),
('Participante 77', 'participante.77@example.com', 'Comunidade'),
('Participante 78', 'participante.78@example.com', 'Professor'),
('Participante 79', 'participante.79@example.com', 'Professor'),
('Participante 80', 'participante.80@example.com', 'Aluno'),
('Participante 81', 'participante.81@example.com', 'Professor'),
('Participante 82', 'participante.82@example.com', 'Professor'),
('Participante 83', 'participante.83@example.com', 'Comunidade'),
('Participante 84', 'participante.84@example.com', 'Comunidade'),
('Participante 85', 'participante.85@example.com', 'Aluno'),
('Participante 86', 'participante.86@example.com', 'Comunidade'),
('Participante 87', 'participante.87@example.com', 'Comunidade'),
('Participante 88', 'participante.88@example.com', 'Comunidade'),
('Participante 89', 'participante.89@example.com', 'Aluno'),
('Participante 90', 'participante.90@example.com', 'Professor'),
('Participante 91', 'participante.91@example.com', 'Aluno'),
('Participante 92', 'participante.92@example.com', 'Comunidade'),
('Participante 93', 'participante.93@example.com', 'Comunidade'),
('Participante 94', 'participante.94@example.com', 'Professor'),
('Participante 95', 'participante.95@example.com', 'Professor'),
('Participante 96', 'participante.96@example.com', 'Comunidade'),
('Participante 97', 'participante.97@example.com', 'Aluno'),
('Participante 98', 'participante.98@example.com', 'Aluno'),
('Participante 99', 'participante.99@example.com', 'Comunidade'),
('Participante 100', 'participante.100@example.com', 'Aluno');

-- INSTRUTORES
INSERT INTO TB_INSTRUTOR (NM_INSTRUTOR, DS_EMAIL, DS_AREA_ESPECIALIDADE) VALUES
('Instrutor 1', 'instrutor.1@example.com', 'Banco de Dados'),
('Instrutor 2', 'instrutor.2@example.com', 'Banco de Dados'),
('Instrutor 3', 'instrutor.3@example.com', 'Banco de Dados'),
('Instrutor 4', 'instrutor.4@example.com', 'Redes'),
('Instrutor 5', 'instrutor.5@example.com', 'Banco de Dados'),
('Instrutor 6', 'instrutor.6@example.com', 'Web'),
('Instrutor 7', 'instrutor.7@example.com', 'Redes'),
('Instrutor 8', 'instrutor.8@example.com', 'Segurança'),
('Instrutor 9', 'instrutor.9@example.com', 'IA'),
('Instrutor 10', 'instrutor.10@example.com', 'Web'),
('Instrutor 11', 'instrutor.11@example.com', 'IA'),
('Instrutor 12', 'instrutor.12@example.com', 'IA'),
('Instrutor 13', 'instrutor.13@example.com', 'Web'),
('Instrutor 14', 'instrutor.14@example.com', 'Redes'),
('Instrutor 15', 'instrutor.15@example.com', 'IA'),
('Instrutor 16', 'instrutor.16@example.com', 'Banco de Dados'),
('Instrutor 17', 'instrutor.17@example.com', 'Banco de Dados'),
('Instrutor 18', 'instrutor.18@example.com', 'Redes'),
('Instrutor 19', 'instrutor.19@example.com', 'Redes'),
('Instrutor 20', 'instrutor.20@example.com', 'Web');

-- PARCEIRAS
INSERT INTO TB_PARCEIRA (NM_PARCEIRA, DS_TIPO, DS_CONTATO) VALUES
('Empresa 1', 'Empresa Privada', 'empresa.1@example.com'),
('Empresa 2', 'ONG', 'empresa.2@example.com'),
('Empresa 3', 'Instituição Pública', 'empresa.3@example.com'),
('Empresa 4', 'Empresa Privada', 'empresa.4@example.com'),
('Empresa 5', 'ONG', 'empresa.5@example.com'),
('Empresa 6', 'ONG', 'empresa.6@example.com'),
('Empresa 7', 'Empresa Privada', 'empresa.7@example.com'),
('Empresa 8', 'Instituição Pública', 'empresa.8@example.com'),
('Empresa 9', 'ONG', 'empresa.9@example.com'),
('Empresa 10', 'ONG', 'empresa.10@example.com');

-- MEMBROS DE APOIO
INSERT INTO TB_MEMBRO_APOIO (NM_MEMBRO_APOIO, DS_PAPEL) VALUES
('Membro 1', 'Voluntário'),
('Membro 2', 'Organizador'),
('Membro 3', 'Organizador'),
('Membro 4', 'Organizador'),
('Membro 5', 'Organizador'),
('Membro 6', 'Organizador'),
('Membro 7', 'Voluntário'),
('Membro 8', 'Organizador'),
('Membro 9', 'Organizador'),
('Membro 10', 'Voluntário'),
('Membro 11', 'Organizador'),
('Membro 12', 'Voluntário'),
('Membro 13', 'Organizador'),
('Membro 14', 'Organizador'),
('Membro 15', 'Voluntário'),
('Membro 16', 'Voluntário'),
('Membro 17', 'Organizador'),
('Membro 18', 'Organizador'),
('Membro 19', 'Voluntário'),
('Membro 20', 'Organizador'),
('Membro 21', 'Voluntário'),
('Membro 22', 'Organizador'),
('Membro 23', 'Voluntário'),
('Membro 24', 'Organizador'),
('Membro 25', 'Organizador'),
('Membro 26', 'Organizador'),
('Membro 27', 'Organizador'),
('Membro 28', 'Organizador'),
('Membro 29', 'Organizador'),
('Membro 30', 'Voluntário');

-- LOCAIS
INSERT INTO TB_LOCAL (NM_LOCAL, DS_TIPO, QT_CAPACIDADE) VALUES
('Auditório Central', 'Sala', 150),
('Sala 101', 'Sala', 30),
('Sala 202', 'Sala', 40),
('Lab. Informática', 'Sala', 25);

-- RECURSOS
INSERT INTO TB_RECURSO (NM_RECURSO, QT_DISPONIVEL) VALUES
('Projetor', 10),
('Notebook', 20),
('Microfone', 15),
('Caixa de som', 5);

-- PROJETOS DE EXTENSÃO
INSERT INTO TB_PROJETO_EXTENSAO (NM_PROJETO, DS_TITULO, NM_RESPONSAVEL, DS_PERIODO) VALUES
('Projeto Comunitário', 'Inclusão digital em comunidades', 'Prof. Lucas Braga', '2025-01 a 2025-12');

-- EVENTO
INSERT INTO TB_EVENTO (NM_EVENTO, DT_INICIO, DT_FIM, DS_EVENTO) VALUES
('Feira de Tecnologia', '2025-06-01', '2025-06-05', 'Feira com exposições e atividades tecnológicas.');

