services:
  postgres:
    build: .
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./backups:/var/lib/postgresql/backups
      - ./logs:/var/log
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - minha-rede

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - minha-rede

volumes:
  postgres_data:
  pgadmin_data:

networks:
  minha-rede:
    driver: bridge
