CREATE TABLE RL_PARTICIPANTE_ATIVIDADE (
    ID_PARTICIPANTE INT NOT NULL,
    ID_ATIVIDADE INT NOT NULL,
    IS_PRESENTE BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID_PARTICIPANTE, ID_ATIVIDADE)
);

CREATE TABLE RL_ATIVIDADE_INSTRUTOR (
    ID_ATIVIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    DS_PAPEL VARCHAR(50),
    PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR)
);

CREATE TABLE RL_ATIVIDADE_PARCEIRA (
    ID_ATIVIDADE INT NOT NULL,
    ID_PARCEIRA INT NOT NULL,
    DS_TIPO VARCHAR(50),
    PRIMARY KEY (ID_ATIVIDADE, ID_PARCEIRA)
);

CREATE TABLE RL_ATIVIDADE_MEMBRO_APOIO (
    ID_ATIVIDADE INT NOT NULL,
    ID_MEMBRO_APOIO INT NOT NULL,
    NR_CARGA_HORARIA INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_ATIVIDADE, ID_MEMBRO_APOIO)
);

CREATE TABLE RL_ATIVIDADE_RECURSO (
    ID_ATIVIDADE INT NOT NULL,
    ID_RECURSO INT NOT NULL,
    NR_QUANTIDADE_UTILIZADO INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_ATIVIDADE, ID_RECURSO)
);

-- Feedback -> Participante
ALTER TABLE TB_FEEDBACK ADD COLUMN ID_PARTICIPANTE INTEGER;
ALTER TABLE TB_FEEDBACK
ADD CONSTRAINT FK_FEEDBACK_PARTICIPANTE
FOREIGN KEY (ID_PARTICIPANTE)
REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE);

-- Feedback -> Atividade
ALTER TABLE TB_FEEDBACK ADD COLUMN ID_ATIVIDADE INTEGER;
ALTER TABLE TB_FEEDBACK
ADD CONSTRAINT FK_FEEDBACK_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

-- Atividade -> Local
ALTER TABLE TB_ATIVIDADE ADD COLUMN ID_LOCAL INTEGER;
ALTER TABLE TB_ATIVIDADE
ADD CONSTRAINT FK_ATIVIDADE_LOCAL
FOREIGN KEY (ID_LOCAL)
REFERENCES TB_LOCAL(ID_LOCAL);

-- Atividade -> Projeto de Extensão
ALTER TABLE TB_ATIVIDADE ADD COLUMN ID_PROJETO_EXTENSAO INTEGER;
ALTER TABLE TB_ATIVIDADE
ADD CONSTRAINT FK_ATIVIDADE_PROJETO
FOREIGN KEY (ID_PROJETO_EXTENSAO)
REFERENCES TB_PROJETO_EXTENSAO(ID_PROJETO_EXTENSAO);

-- Certificado -> Atividade
ALTER TABLE TB_CERTIFICADO ADD COLUMN ID_ATIVIDADE INTEGER;
ALTER TABLE TB_CERTIFICADO
ADD CONSTRAINT FK_CERTIFICADO_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

-- Certificado -> Participante
ALTER TABLE TB_CERTIFICADO ADD COLUMN ID_PARTICIPANTE INTEGER;
ALTER TABLE TB_CERTIFICADO
ADD CONSTRAINT FK_CERTIFICADO_PARTICIPANTE
FOREIGN KEY (ID_PARTICIPANTE)
REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE);

-- Ocorrência -> Atividade
ALTER TABLE TB_OCORRENCIA ADD COLUMN ID_ATIVIDADE INTEGER;
ALTER TABLE TB_OCORRENCIA
ADD CONSTRAINT FK_OCORRENCIA_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

-- Atividade -> Evento
ALTER TABLE TB_ATIVIDADE ADD COLUMN ID_EVENTO INTEGER;
ALTER TABLE TB_ATIVIDADE
ADD CONSTRAINT FK_ATIVIDADE_EVENTO
FOREIGN KEY (ID_EVENTO)
REFERENCES TB_EVENTO(ID_EVENTO);

-- Participante <-> Atividade
ALTER TABLE RL_PARTICIPANTE_ATIVIDADE
ADD CONSTRAINT FK_RL_PARTICIPANTE_ATIVIDADE_PARTICIPANTE
FOREIGN KEY (ID_PARTICIPANTE)
REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE);

ALTER TABLE RL_PARTICIPANTE_ATIVIDADE
ADD CONSTRAINT FK_RL_PARTICIPANTE_ATIVIDADE_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

-- Atividade <-> Instrutor
ALTER TABLE RL_ATIVIDADE_INSTRUTOR
ADD CONSTRAINT FK_RL_ATIVIDADE_INSTRUTOR_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

ALTER TABLE RL_ATIVIDADE_INSTRUTOR
ADD CONSTRAINT FK_RL_ATIVIDADE_INSTRUTOR_INSTRUTOR
FOREIGN KEY (ID_INSTRUTOR)
REFERENCES TB_INSTRUTOR(ID_INSTRUTOR);

-- Atividade <-> Parceira
ALTER TABLE RL_ATIVIDADE_PARCEIRA
ADD CONSTRAINT FK_RL_ATIVIDADE_PARCEIRA_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

ALTER TABLE RL_ATIVIDADE_PARCEIRA
ADD CONSTRAINT FK_RL_ATIVIDADE_PARCEIRA_PARCEIRA
FOREIGN KEY (ID_PARCEIRA)
REFERENCES TB_PARCEIRA(ID_PARCEIRA);

-- Atividade <-> Membro Apoio
ALTER TABLE RL_ATIVIDADE_MEMBRO_APOIO
ADD CONSTRAINT FK_RL_ATIVIDADE_MEMBRO_APOIO_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

ALTER TABLE RL_ATIVIDADE_MEMBRO_APOIO
ADD CONSTRAINT FK_RL_ATIVIDADE_MEMBRO_APOIO_MEMBRO
FOREIGN KEY (ID_MEMBRO_APOIO)
REFERENCES TB_MEMBRO_APOIO(ID_MEMBRO_APOIO);

-- Atividade <-> Recurso
ALTER TABLE RL_ATIVIDADE_RECURSO
ADD CONSTRAINT FK_RL_ATIVIDADE_RECURSO_ATIVIDADE
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES TB_ATIVIDADE(ID_ATIVIDADE);

ALTER TABLE RL_ATIVIDADE_RECURSO
ADD CONSTRAINT FK_RL_ATIVIDADE_RECURSO_RECURSO
FOREIGN KEY (ID_RECURSO)
REFERENCES TB_RECURSO(ID_RECURSO);
