-- Tabelas principais
CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE SERIAL PRIMARY KEY,
    NM_PARTICIPANTE VARCHAR(100) NOT NULL,
    DS_EMAIL VARCHAR(100),
    TP_PARTICIPANTE VARCHAR(50)
);

CREATE TABLE TB_FEEDBACK (
    ID_FEEDBACK SERIAL PRIMARY KEY,
    NR_NOTA INTEGER,
    DS_COMENTARIO TEXT,
    DT_FEEDBACK DATE
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL PRIMARY KEY,
    DT_ATIVIDADE DATE NOT NULL,
    NM_ATIVIDADE VARCHAR(100) NOT NULL,
    DS_ATIVIDADE TEXT,
    QT_CARGA_HORARIA INTEGER
);

CREATE TABLE TB_INSTRUTOR (
    ID_INSTRUTOR SERIAL PRIMARY KEY,
    NM_INSTRUTOR VARCHAR(100) NOT NULL,
    DS_EMAIL VARCHAR(100),
    DS_AREA_ESPECIALIDADE VARCHAR(100)
);

CREATE TABLE TB_PARCEIRA ( 
    ID_PARCEIRA SERIAL PRIMARY KEY,
    NM_PARCEIRA VARCHAR(100) NOT NULL,
    DS_TIPO VARCHAR(50),
    DS_CONTATO VARCHAR(100)
);

CREATE TABLE TB_MEMBRO_APOIO (
    ID_MEMBRO_APOIO SERIAL PRIMARY KEY,
    NM_MEMBRO_APOIO VARCHAR(100) NOT NULL,
    DS_PAPEL VARCHAR(50)
);

CREATE TABLE TB_LOCAL (
    ID_LOCAL SERIAL PRIMARY KEY,
    NM_LOCAL VARCHAR(100) NOT NULL,
    DS_TIPO VARCHAR(50),
    QT_CAPACIDADE INTEGER
);

CREATE TABLE TB_RECURSO (
    ID_RECURSO SERIAL PRIMARY KEY,
    NM_RECURSO VARCHAR(100) NOT NULL,
    QT_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE TB_PROJETO_EXTENSAO (
    ID_PROJETO_EXTENSAO SERIAL PRIMARY KEY,
    NM_PROJETO VARCHAR(100) NOT NULL,
    DS_TITULO VARCHAR(150) NOT NULL,
    NM_RESPONSAVEL VARCHAR(100),
    DS_PERIODO VARCHAR(50)
);

CREATE TABLE TB_CERTIFICADO (
    ID_CERTIFICADO SERIAL PRIMARY KEY,
    DT_EMISSAO DATE NOT NULL,
    DS_TITULO VARCHAR(100),
    DS_DESCRICAO TEXT,
    CD_VERIFICACAO VARCHAR(50)
);

CREATE TABLE TB_OCORRENCIA (
    ID_OCORRENCIA SERIAL PRIMARY KEY,
    DH_OCORRENCIA TIMESTAMP NOT NULL,
    DS_TIPO VARCHAR(50),
    DS_DESCRICAO TEXT
);

CREATE TABLE TB_EVENTO (
    ID_EVENTO SERIAL PRIMARY KEY,
    NM_EVENTO VARCHAR(100) NOT NULL,
    DT_INICIO DATE,
    DT_FIM DATE,
    DS_EVENTO TEXT
);